function departmentAutocomplete() {
    console.log('asdf');
    var departmentList = [
        "Aerospace Studies (Air Force ROTC)",
        "African American Studies",
        "Agricultural and Resource Economics",
        "American Studies",
        "Ancient History and Mediterranean Archaeology",
        "Anthropology",
        "Applied Science and Technology",
        "Arabic",
        "Architecture",
        "Asian American Studies",
        "Asian Studies",
        "Astronomy",
        "Bengali",
        "Bioengineering",
        "Biology (General)",
        "Biophysics",
        "Biostatistics",
        "Buddhist Studies",
        "Business Administration",
        "Business Administration -​ MBA",
        "Business Administration -​ PhD",
        "Business Administration -​ Undergraduate",
        "Catalan",
        "Celtic Studies",
        "Chemical and Biomolecular Engineering",
        "Chemistry (College of)",
        "Chemistry (Department of)",
        "Chicano Studies",
        "Chinese",
        "City and Regional Planning",
        "Civil and Environmental Engineering",
        "Classics",
        "Cognitive Science",
        "College Writing Programs",
        "Comparative Biochemistry",
        "Comparative Literature",
        "Computational Biology",
        "Computational and Genomic Biology",
        "Computer Science (Engineering)",
        "Computer Science (Letters and Science)",
        "Critical Theory",
        "Cuneiform",
        "Demography",
        "Development Practice",
        "Development Studies",
        "Dutch Studies",
        "Earth and Planetary Science",
        "East Asian Languages and Cultures",
        "East European Studies",
        "Economics",
        "Education",
        "Egyptian",
        "Electrical Engineering",
        "Electrical Engineering and Computer Sciences",
        "Endocrinology",
        "Energy and Resources Group",
        "Engineering",
        "Engineering Science",
        "Engineering-​-​Joint Major Programs",
        "Engineering-​-​Undeclared",
        "English",
        "Environmental Design",
        "Environmental Economics and Policy",
        "Environmental Health Sciences",
        "Environmental Science, Policy and Management",
        "Environmental Sciences",
        "Epidemiology",
        "Ethnic Studies",
        "Ethnic Studies Graduate Group",
        "Eurasian Studies",
        "Evening and Weekend MBA",
        "Executive MBA",
        "Filipino",
        "Film and Media",
        "Financial Engineering",
        "Folklore",
        "French",
        "Gender and Women's Studies",
        "Geography",
        "German",
        "Global Metropolitan Studies",
        "Global Poverty and Practice",
        "Graduate Student Professional Development Program",
        "Greek: Classical",
        "Health Services and Policy Analysis",
        "Health and Medical Sciences Program",
        "Hebrew",
        "Hindi-​Urdu",
        "History",
        "History of Art",
        "Industrial Engineering and Operations Research",
        "Infectious Diseases and Immunity",
        "Information",
        "Integrative Biology",
        "Interdisciplinary Studies",
        "International and Area Studies",
        "Iranian",
        "Italian Studies",
        "Japanese",
        "Jewish Studies",
        "Joint Medical Program, UCB-​UCSF",
        "Journalism",
        "Jurisprudence and Social Policy",
        "Khmer",
        "Korean",
        "Landscape Architecture and Environmental Planning",
        "Language Proficiency Program",
        "Latin",
        "Latin American Studies",
        "Law",
        "Legal Studies",
        "Lesbian, Gay, Bisexual, and Transgender Studies",
        "Letters and Science",
        "Linguistics",
        "Logic and the Methodology of Science",
        "Malay/​Indonesian",
        "Materials Science and Engineering",
        "Mathematics",
        "Mechanical Engineering",
        "Media Studies",
        "Medical Anthropology",
        "Medieval Studies",
        "Microbiology",
        "Middle Eastern Studies",
        "Military Affairs",
        "Military Officers' Education Program",
        "Military Science (Army ROTC)",
        "Molecular and Cell Biology",
        "Music",
        "Nanoscale Science and Engineering",
        "Native American Studies",
        "Natural Resources",
        "Naval Science (Naval ROTC)",
        "Near Eastern Studies",
        "Neuroscience",
        "New Media",
        "Nuclear Engineering",
        "Nutritional Science and Toxicology",
        "Optometry",
        "Peace and Conflict Studies",
        "Persian",
        "Philosophy",
        "Physical Education",
        "Physics",
        "Plant and Microbial Biology",
        "Political Economy",
        "Political Science",
        "Portuguese",
        "Practice of Art",
        "Psychology",
        "Public Health",
        "Public Policy",
        "Punjabi",
        "Range Management",
        "Religious Studies",
        "Rhetoric",
        "Romance Languages and Literatures",
        "Sanskrit",
        "Scandinavian",
        "Science and Mathematics Education",
        "Science and Technology Studies",
        "Semitics",
        "Slavic Languages and Literatures",
        "Social Welfare",
        "Sociology",
        "Sociology and Demography",
        "South Asian",
        "South and Southeast Asian Studies",
        "Southeast Asian",
        "Spanish and Portuguese",
        "Statistics",
        "Sustainable Environmental Design ",
        "Tamil",
        "Telugu",
        "Thai",
        "Theater, Dance, and Performance Studies",
        "Tibetan",
        "Turkish",
        "Undergraduate and Interdisciplinary Studies",
        "Urban Design",
        "Urban Studies",
        "Vietnamese",
        "Vision Science",
        "Visual Studies",
        "Yiddish"
    ];

    $('#inputDepartment').autocomplete({source: departmentList});
}